---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure NGINX
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx site configurations
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/laravel.conf

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/laravel.conf
    dest: /etc/nginx/sites-enabled/laravel.conf
    state: link

- name: Ensure Nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
